project:
  type: website
  output-dir: docs # keeps the file if i am deploying via /docs; change if using actions

website:
  title: "Charles Batsaikhan"  # shows top-left as my name 
  navbar:
    left: []
    right:
      - href: about.qmd
        text: About 
      - href: resume.qmd
        text: Resume
      - href: projects.qmd
        text: Projects
      - href: visuals.qmd
        text: Visualizations
  page-footer: 
    left: |
      &copy; Charles Batsaikhan, 2023<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>


format:
  html:
    theme: flatly
    toc: false
    css: styles.css
    smooth-scroll: true
    include-after-body: []

 




    


